Add a section on common issues
yeatmanlab/create-roar-app pull request #4
Opened 2022-10-04 20:45 UTC by Mohammed-Shoaib

### Notes

* Create a new section on common issues and update the navigation page.
* Move the section on advice for asset files and audio stimuli to common issues.
* Small changes such as content tabs and typo.

### Testing

* Install [MkDocs](https://www.mkdocs.org/) by following the [documentation](https://www.mkdocs.org/user-guide/installation/).
* Use `mkdocs serve` and manually check the changes.

2022-10-04 22:08 UTC, richford commented on docs/docs/developer-guide/installation.md
> +
Not sure why we need `tsup` here.

2022-10-04 22:08 UTC, richford requested changes
@Mohammed-Shoaib, this looks good, thanks! I just have one correction which is that I'm not sure why we need `tsup`.

2022-10-05 16:26 UTC, Mohammed-Shoaib commented
Thank you for the review, Adam!

I got the an error when running `npm start`:

```
tsc: command not found
```

I had typescript installed. Installing `tsup` fixed the issue for me.

Do you have `tsup` installed on your machine?

2022-10-05 18:19 UTC, richford approved these changes

2022-10-05 18:19 UTC, Mohammed-Shoaib commented
Updated to remove the instructions on `tsup`!

2022-10-05 18:19 UTC, merged